/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/model.glb
*/

import React, { useEffect, useState } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import { useAtom } from "jotai";
import { activeAnimationAtom } from "@/src/jotai/atoms";

export function Model(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("models/model.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  const [activeAnimation, setActiveAnimation] = useAtom(activeAnimationAtom);


  useEffect(() => {
    // متوقف کردن تمام انیمیشن‌ها
    Object.values(actions).forEach(action => action.stop());

    // شروع انیمیشن فعال
    if (actions[activeAnimation]) {
      actions[activeAnimation].play();
    }

    return () => {
      // پاک‌سازی انیمیشن‌ها در هنگامUnmount
      Object.values(actions).forEach(action => action.stop());
    };
  }, [activeAnimation, actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Breath" scale={0.01}>
          <primitive object={nodes.CC_Base_BoneRoot} />
          <group name="CC_Base_Body">
            <skinnedMesh
              name="CC_Base_Body_1"
              geometry={nodes.CC_Base_Body_1.geometry}
              material={materials.Std_Skin_Head}
              skeleton={nodes.CC_Base_Body_1.skeleton}
            />
            <skinnedMesh
              name="CC_Base_Body_2"
              geometry={nodes.CC_Base_Body_2.geometry}
              material={materials.Std_Skin_Body}
              skeleton={nodes.CC_Base_Body_2.skeleton}
            />
            <skinnedMesh
              name="CC_Base_Body_3"
              geometry={nodes.CC_Base_Body_3.geometry}
              material={materials.Std_Skin_Arm}
              skeleton={nodes.CC_Base_Body_3.skeleton}
            />
            <skinnedMesh
              name="CC_Base_Body_4"
              geometry={nodes.CC_Base_Body_4.geometry}
              material={materials.Std_Skin_Leg}
              skeleton={nodes.CC_Base_Body_4.skeleton}
            />
            <skinnedMesh
              name="CC_Base_Body_5"
              geometry={nodes.CC_Base_Body_5.geometry}
              material={materials.Std_Nails}
              skeleton={nodes.CC_Base_Body_5.skeleton}
            />
            <skinnedMesh
              name="CC_Base_Body_6"
              geometry={nodes.CC_Base_Body_6.geometry}
              material={materials.Std_Eyelash}
              skeleton={nodes.CC_Base_Body_6.skeleton}
            />
          </group>
          <group name="CC_Base_Eye">
            <skinnedMesh
              name="CC_Base_Eye_1"
              geometry={nodes.CC_Base_Eye_1.geometry}
              material={materials.Std_Eye_R}
              skeleton={nodes.CC_Base_Eye_1.skeleton}
            />
            <skinnedMesh
              name="CC_Base_Eye_2"
              geometry={nodes.CC_Base_Eye_2.geometry}
              material={materials.Std_Cornea_R}
              skeleton={nodes.CC_Base_Eye_2.skeleton}
            />
            <skinnedMesh
              name="CC_Base_Eye_3"
              geometry={nodes.CC_Base_Eye_3.geometry}
              material={materials.Std_Eye_L}
              skeleton={nodes.CC_Base_Eye_3.skeleton}
            />
            <skinnedMesh
              name="CC_Base_Eye_4"
              geometry={nodes.CC_Base_Eye_4.geometry}
              material={materials.Std_Cornea_L}
              skeleton={nodes.CC_Base_Eye_4.skeleton}
            />
          </group>
          <group name="CC_Base_EyeOcclusion">
            <skinnedMesh
              name="CC_Base_EyeOcclusion_1"
              geometry={nodes.CC_Base_EyeOcclusion_1.geometry}
              material={materials.Std_Eye_Occlusion_R}
              skeleton={nodes.CC_Base_EyeOcclusion_1.skeleton}
            />
            <skinnedMesh
              name="CC_Base_EyeOcclusion_2"
              geometry={nodes.CC_Base_EyeOcclusion_2.geometry}
              material={materials.Std_Eye_Occlusion_L}
              skeleton={nodes.CC_Base_EyeOcclusion_2.skeleton}
            />
          </group>
          <group name="CC_Base_TearLine">
            <skinnedMesh
              name="CC_Base_TearLine_1"
              geometry={nodes.CC_Base_TearLine_1.geometry}
              material={materials.Std_Tearline_R}
              skeleton={nodes.CC_Base_TearLine_1.skeleton}
            />
            <skinnedMesh
              name="CC_Base_TearLine_2"
              geometry={nodes.CC_Base_TearLine_2.geometry}
              material={materials.Std_Tearline_L}
              skeleton={nodes.CC_Base_TearLine_2.skeleton}
            />
          </group>
          <group name="CC_Base_Teeth">
            <skinnedMesh
              name="CC_Base_Teeth_1"
              geometry={nodes.CC_Base_Teeth_1.geometry}
              material={materials.Std_Upper_Teeth}
              skeleton={nodes.CC_Base_Teeth_1.skeleton}
            />
            <skinnedMesh
              name="CC_Base_Teeth_2"
              geometry={nodes.CC_Base_Teeth_2.geometry}
              material={materials.Std_Lower_Teeth}
              skeleton={nodes.CC_Base_Teeth_2.skeleton}
            />
          </group>
          <skinnedMesh
            name="CC_Base_Tongue"
            geometry={nodes.CC_Base_Tongue.geometry}
            material={materials.Std_Tongue}
            skeleton={nodes.CC_Base_Tongue.skeleton}
          />
          <skinnedMesh
            name="Chin_Curtain_Sparse"
            geometry={nodes.Chin_Curtain_Sparse.geometry}
            material={materials["Beard_Transparency.001"]}
            skeleton={nodes.Chin_Curtain_Sparse.skeleton}
          />
          <skinnedMesh
            name="Fit_shirts"
            geometry={nodes.Fit_shirts.geometry}
            material={materials.Fit_shirts}
            skeleton={nodes.Fit_shirts.skeleton}
          />
          <skinnedMesh
            name="Haircut"
            geometry={nodes.Haircut.geometry}
            material={materials.obj_default_Transparency}
            skeleton={nodes.Haircut.skeleton}
          />
          <skinnedMesh
            name="Slim_fit_pants"
            geometry={nodes.Slim_fit_pants.geometry}
            material={materials.Slim_fit_pants}
            skeleton={nodes.Slim_fit_pants.skeleton}
          />
          <skinnedMesh
            name="Sport_sneakers"
            geometry={nodes.Sport_sneakers.geometry}
            material={materials.Sport_sneakers}
            skeleton={nodes.Sport_sneakers.skeleton}
          />
          <skinnedMesh
            name="Stubble_Neck"
            geometry={nodes.Stubble_Neck.geometry}
            material={materials.Beard_Transparency}
            skeleton={nodes.Stubble_Neck.skeleton}
          />
          <skinnedMesh
            name="Toxido"
            geometry={nodes.Toxido.geometry}
            material={materials.surfacematerial1}
            skeleton={nodes.Toxido.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/model.glb");
