import localFont from "next/font/local";
import "./globals.css";
import { Provider } from "jotai";
import { createStore } from "jotai";

export const jotaiStore = createStore();

export const metadata = {
  title: "MCIChatBot",
  description: "Generated by MCI R&D Center",
};

const iranSansFont = localFont({
  src: "../public/fonts/IRANSansXV.woff2",
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="" dir="rtl">
      <Provider>
        <body className={iranSansFont.className}>{children}</body>
      </Provider>
    </html>
  );
}
